kind: pipeline
name: react-redux

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test

  - name: build
    image: node
    commands:
      - npm run dist

  - name: add_to_git
    image: docker:git
      - git add .
      - git commit -m "new release"

  - name: deploy
    image: docker:git
    commands:
      - git push heroku master