language: node_js
node_js:
  - '14'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm install
script:
  - npm test
  - npm run dist
  - npm run test:ci
deploy:
  provider: heroku
  app: reactredux-fr
  skip_cleanup: true
  api_key:
    secure: mpriTk8wh4AadVb7fSqyZ1ge6OQWRO7rfSwZxQM+cO366mFl+siTk7ULlO0bXvHEQ66rFXK7/lNDthdtjbqQlD6DPIvr37D5wE4C3xuKcHVYj9TdO1ZKh+xMEQPk8EVCn/qbG/cUEEl6NyXhFlLp9eBMPVr6Zb5k6wy/OuCWfm9m5tkBfwN8ThFL08On+Jebn35MwYfyQOuMOL1HaPYCuXiqYQGzzD2pZeEkiNQIT1CE2zFI2EobFj20q0XIRwvY3eTlQASeNuVDjahPVlHJV6Y71ysa/ZlHOidjf7Usnls+iZ13rw3IGd7sDQ+onkrA9fSeZCdvdZ5FFuPYirIlZWRDWV/wrNL2nuinF5Q2oMMH+TW8c2TFy9o8Fh/DH4+4NA7bGyYeZIvmBX3OWP3q1j/KG1k8sz0LzVbu9MIzC9zwpq+HEi0dXVumgtn3Aff1DdrN6+vy3c2RBhKmGR+JZeTgonKq0iPPmWrbpDWqH1T/HWRK82GIEqX1vos8zITYD024XKXbqLB7VA2+AngiWSfDG1yJGyD12qecTurwlEiyE1a9GpgudKZfpFaxuYT681VobJ6fiGRWpxSBOOtZivhGsoSf6CdA1HU4oPRF3khQWY30PwOSzCnaKg+J5Z0w7a1cfFIfcmq72c62nzYOFlKRnWwsBCpAuH9+0FSTltU=
