language: node_js
node_js:
  - '12'
install:
  - npm install
script:
  - npm test
  - npm run dist
deploy:
  provider: heroku
  app: reactredux-fr
  skip_cleanup: true
  api_key:
    secure: ZqZW4IxOT5ugGv/sVdaVY9gxRTNk8HY6KlzxPiZyumf28QfbC4W6VmdmSMRVIOsqTOJN4fWlEsboXXkO1JUrUP4gi3Yx1rNnPUo2MvEVCVHCuWr3Ro9BMj//ZFccsE4QQ3jaJ2DYxJ/UP9nzeTDpXrfh4wGxDfCRv5nIHL3htriTS7zp6TwkAr2ONJ43kpZQRiySg8udfgRiq0wnTucubX28nh/Ik64c1OoyneQTY2SE2oLpXiRmUmSidALmzanyR2Z4rfkNpIs6I5pGVOUwGEzFzbv7m7Hudn5Vj2P8KPZrXu0HD5XWNkrhKo6uhlWoqpcfdxn0HT4Wt07Zl2WeAbHEASs/Lg9d4LIIdVVgTX5UqvZ3MX1QSjIRfZa7rureKUq8ZvEKw5ePxTwvFJ4QMo9sYNqmSML5JtWNkOupJMerCN9Euyk4OXOGdLq4H0IsIYkUhirZesTcOqu3oGI15+Ai3cCnkRw9kCn3Ca7Dokb2PJwdw/NWuA2YvxXoA6n2HqwsMFC6cAxCAdK/NlS5rQ3Bp4almL7cDGuVOfi7bqyo4Ifw4+VFNFXE7Kzb/JPqm9KdG8mKn12EpG+339YOI3mwrt+0G/LRwMN4jug+yBROvfIFI74pCC6shPYRNDzwpRbwIUhRtEkm1RVs9zdaecLB7LyG4Tor5IYZhs+VNAI=
