language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm test
- npm run dist
deploy:
  provider: heroku
  app: reactredux-fr
  skip_cleanup: true
  api_key:
    secure: pU/FOyWW48ghGoHQUpI4PIYHUIhVpFTQdXbN/DPg4L1BxADtlK9jOSndDG+Scd4voapM37EaGDg60vSduzUgPM+BvdOvF3jXwR7PAp1BAfDy8ksdNX+yqzQKcbAPCFdaGzuq5PMfC3iNBgHNBR2mRzKY4jXx9OMvgHtglWytAhmIqB+zLwNKWLq2uTpMEN4OYDNRNUTHtWVAKr7js+1FeSkS2e8ezcq5fmOoV8/SyVtNts38W27KmQstsK85GItbsa8mho5vAax47gXWQfpw1q0gQJDRG9kipWzQzvoV3P0UPOjutJii37Uu9ESwUG6rg38KL6MRspoTywQIcd5VsrJ95jmFZ0iRxdS0s49lbkQ7E+OAt0y/Gzy5Fmt5wUYs6VbO3t0BcH73PcfNhsLQnsOQT4CuSURZDp+5O1OGzFaDm+CR3SwKNbTeY5GtWLN+iI02ochCASrxtiXQOiCnqzK4Mwu203J/8wAWq0nA8OTnXF4mWkVdhSXJKxoMcqndD9naV3sIKJE4njqO7fYIHA1HDEL6ha7yIrnbre4alRpDThw7EOIjrOkFfzqsScDhNYFj7T/5xRPo8p3Wj5yF4Jjk/UMj9lXXEj1B0X6Xbe51xSov4uldKkFRpWbodArJoW9GxIXZre1od3UDULwWjCiwpE3MqC1imZqRgc1VpCU=
