language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
addons:
  apt:
    packages:
      - libgconf-2-4
before_cache:
  - rm -rf $HOME/.cache/Cypress
cache:
  npm: true
  directories:
    - '~/.cache'
install:
  - npm install
script:
  - npm test
  - npm run dist
  - npm run test:ci
deploy:
  provider: heroku
  app: reactredux-fr
  skip_cleanup: true
  api_key:
    secure: l7NVz3qAuzA1rIuj9DYkvHNH8mu8Nau3ovHJ30KvZ4oyQ/46LQmA2EsyxIQYFDHyPpwdcfQ8fFIgz9YEsGvI75bexQuupr/R05Q08DwbxFZR3EtXf1CzFhX7m+xCamur+fDSkfX/pKNqjlNdlBbLJDPc74gsH7Fm57ep2okXn241KD754M8WltFSOetEVn9CFGFdsZJ64TX3UZ/hcU64JOOI9kotjKRPpCdjZHz+SjoWDs6KPCI3gvaAjwPLUFon0fX43DhSqWRD++HX6dgY5YIlUGQoHhge/F1k/YqOyWJ9UT+aMvJFlOM4MhQy+SaVNo/a2o1IvUjjq2FwUNzOaEpEDFz+/qz/TH9BsS2XoIm2BbvkCNP4Je1WuxnT4ubH5WUiZZ8bEyN6OqxyDfSBtzHb6C59d/muMZtnoBPy2udr/VNKo18thHTIuJSN7XxfSdpyAyp8FinUHBoR6N0t31yXtdvvTSCs02K6PLev18oO6YfoRfDUh8/6xe+yBIyOL7zcahoJUwtkWZhHOa86FfL1GoDo3uPfqOJK5cz8cInigi2/rxuMDBRhqLj3Nqu7JS9r0+7VnbvdYwXj2c6tF5CEv5Ozz5YQUBEDs5rH/rAC0huMkZ5PuXzHuJm+VXVU6mRk9hq3F/l23WpYAmVG69aj9qV/o8JhE2nCFPwj/Us=
