language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - '~/.cache'
install:
  - npm install
script:
  - npm test
  - npm run dist
  - npm run test:ci
deploy:
  provider: heroku
  app: reactredux-fr
  skip_cleanup: true
  api_key:
    secure: A0PttAiFN9UURWqI3zGVRAWfkY4yBCkUm8pkZ6YayQeJWoYmWW32Ip0pxqnvJ3odCRnJSHAM7XgoxNWoEEfR/fTOvexF2F36XjaovVyPQYeMEZ7rUR4s220K74mXX92GdNZ75oWGO9CRX+X9HsQvlnRkIOpSklOW5XiD4OWl00SrKQ8bpfbwiJFkVmXGFQRYiuH2UycBzYYGC1/u4JUxqjIOk8cX5vj08eGf7kIAOA8CuCtYTILdnNeC0eGD/xg6MR9cDHVmSAsofNrjbwfsVK31gsqeGfPg6V8p/0nGYaa2ux2/Jd+XjTFfwuvtKFA/Sd7YhTzbKm66G8PVwVaZByAitrNPUNyD1AoqKTnQLXy5fzdhegmUIuzz7H4PiC+hrziywqONkViiBJZW60xAPpL86I5TRRhkG3oRoyTDAC9DkzeJEJkOEd2E8Hcw/uKJTWbwMCByAdZ9l5xKoxR5hRXilCXTIiL7AEh5Nq0rq8NLclvmNKsPSw/MtrtbNvmAENiR+U0vecSX3GItEFPKZYkbivfdphOd6hbG/DZkxC0TjPvmdymGXURfWX2tZ8ZHYW2Cm+XZH6f8ePfn93eUuM6uhCmSWgw6G/HPWrXv3ZylaWPtKh0PUP2idSCTvTFxIbUd3Hbf0upyXnrRUJI+qNia0diGk0ZmYtQLP5Ll5TU=
