name: Test and deploy yo Heroku
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install deps
        run: npm i
  unittest:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    needs: 'install'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm i
      - run: npm test
  e2etest:
    name: 'End2end tests'
    runs-on: ubuntu-latest
    needs: 'install'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm i
      - run: npm run test:ci
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: ['unittest', 'e2etest']
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run dist
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'reactredux-fr'
          heroku_email: 'florent.duveau@gmail.com'
